-- Version: 7
-- Load season data
INSERT INTO season (series_id, name) VALUES
    ((SELECT id FROM series WHERE name = 'Deep Space Nine'), 'Season 1'),
    ((SELECT id FROM series WHERE name = 'Deep Space Nine'), 'Season 2'),
    ((SELECT id FROM series WHERE name = 'Deep Space Nine'), 'Season 3'),
    ((SELECT id FROM series WHERE name = 'Deep Space Nine'), 'Season 4'),
    ((SELECT id FROM series WHERE name = 'Deep Space Nine'), 'Season 5'),
    ((SELECT id FROM series WHERE name = 'Deep Space Nine'), 'Season 6'),
    ((SELECT id FROM series WHERE name = 'Deep Space Nine'), 'Season 7'),
    ((SELECT id FROM series WHERE name = 'Enterprise'), 'Season 1'),
    ((SELECT id FROM series WHERE name = 'Enterprise'), 'Season 2'),
    ((SELECT id FROM series WHERE name = 'Enterprise'), 'Season 3'),
    ((SELECT id FROM series WHERE name = 'Enterprise'), 'Season 4'),
    ((SELECT id FROM series WHERE name = 'The Next Generation'), 'Movies'),
    ((SELECT id FROM series WHERE name = 'The Next Generation'), 'Season 1'),
    ((SELECT id FROM series WHERE name = 'The Next Generation'), 'Season 2'),
    ((SELECT id FROM series WHERE name = 'The Next Generation'), 'Season 3'),
    ((SELECT id FROM series WHERE name = 'The Next Generation'), 'Season 4'),
    ((SELECT id FROM series WHERE name = 'The Next Generation'), 'Season 5'),
    ((SELECT id FROM series WHERE name = 'The Next Generation'), 'Season 6'),
    ((SELECT id FROM series WHERE name = 'The Next Generation'), 'Season 7'),
    ((SELECT id FROM series WHERE name = 'The Original Series'), 'Movies'),
    ((SELECT id FROM series WHERE name = 'The Original Series'), 'Season 1'),
    ((SELECT id FROM series WHERE name = 'The Original Series'), 'Season 2'),
    ((SELECT id FROM series WHERE name = 'The Original Series'), 'Season 3'),
    ((SELECT id FROM series WHERE name = 'Voyager'), 'Season 1'),
    ((SELECT id FROM series WHERE name = 'Voyager'), 'Season 2'),
    ((SELECT id FROM series WHERE name = 'Voyager'), 'Season 3'),
    ((SELECT id FROM series WHERE name = 'Voyager'), 'Season 4'),
    ((SELECT id FROM series WHERE name = 'Voyager'), 'Season 5'),
    ((SELECT id FROM series WHERE name = 'Voyager'), 'Season 6'),
    ((SELECT id FROM series WHERE name = 'Voyager'), 'Season 7');