-- Version: 9
-- Load tag data
INSERT INTO tag (name) VALUES
    ('B''Elanna'),
    ('Barclay'),
    ('Bashir'),
    ('Best'),
    ('Chakotay'),
    ('Crusher'),
    ('Data'),
    ('Dax'),
    ('Doctor'),
    ('Dominion'),
    ('Dukat'),
    ('Essential'),
    ('Ferengi'),
    ('Garak'),
    ('Holodeck'),
    ('Jake'),
    ('Janeway'),
    ('Kazon'),
    ('Kes'),
    ('Kim'),
    ('Kira'),
    ('Kirk'),
    ('Klingons'),
    ('La Forge'),
    ('Lwaxana'),
    ('Mirror'),
    ('Neelix'),
    ('Nog'),
    ('O''Brien'),
    ('Odo'),
    ('Paris'),
    ('Picard'),
    ('Q'),
    ('Quark'),
    ('Riker'),
    ('Romulans'),
    ('Seven'),
    ('Sisko'),
    ('Species 8472'),
    ('Spock'),
    ('Troi'),
    ('Tuvok'),
    ('Vic'),
    ('Wesley'),
    ('Worf'),
    ('Yar');